### ISSUE TITLE
my modified version of sharif judge

### ISSUE THREAD

**Issue by ngoaho91** [mjnaderi/Sharif-Judge#1]
Hello sharif, i'm developing another version of sharif judge, for using in my colledge as a contest & practice enviroment.
Is there a problem if i use it as a colledge project, non commercial i promise???? I don't understand much about GPL.
Also, there are some features i develop
- C# judge. C# not usually used in contest, but everyone in my colledge learn C#. It's good for beginner while they do not have to learn a new language to join algorithmic community.
- Practice mode, which no submit time limit and ranking.
- Optimize database. As the practice mode added, submission also grown. I do some optimization to make it more stabble when store large data. It's not best optimization yet i think, but it works well if submission does not reach million :D

p/s: here is the link https://github.com/ngoaho91/sharif-judge

**Comment by mjnaderi** [comment]
Hi.
There is no problem. Glad to hear that :)
Here is a quick summary about GPL v3:
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)
