### ISSUE TITLE
Adding another language

### ISSUE THREAD

**Issue by kadirovazizbek** [mjnaderi/Sharif-Judge#14]
Hello!
I just wanted to add some another languages, for example, Pascal.
I think, I have to install fpc (Free Pascal Compiler) on my server? What files should I edit to add new compiler? Do you plan to add another languages in the future?

**Comment by mjnaderi** [comment]
Hi,
Adding a new language needs sandboxing, for security.
There is no general sandbox in Sharif Judge for providing security in all languages. We do different things for sandboxing different languages. And Sharif Judge doesn't have a complete solution for sandboxing Python.
So I have not any plan to add new languages. We need a general solution for sandboxing (e.g. a virtual machine), before trying to add new languages.
If you want to add a new language, take a look at `tester/tester.sh`, `application/helpers/shj_helper.php`,`application/controllers/Submit.php`, `application/controllers/Queueprocess.php`, `application/controllers/Assignments.php`, `application/views/pages/admin/add_assignment.twig`, `application/models/Assignment_model.php`.

`tester.sh` is the main file (a Bash script) that runs submitted codes.

**Comment by kadirovazizbek** [comment]
Thanks a lot! You did a great work

**Comment by thezawad** [comment]
Do you mean that making modification on tester.sh to compile and run other languages can get me working with another language? for example I want PHP as a language. any suggestion with that?

**Comment by bhzhu203** [comment]
I think  docker is a solution for  sandbox.

**Comment by shanto31** [comment]
I mean sample code

**Comment by DiegoQueiroz** [comment]
I do not know why do you guys care so much about Sandboxing. I am not telling security is not important, but chroot + run as unplivileged user seems enough for most cases, at least for me.

BTW, my users are cool. They won't harm my server. And, if they do, a backup is everything I need.
