### ISSUE TITLE
You cannot change your final submissions after assignment finishes

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#17]
You cannot change your final submissions after assignment finishes

**Comment by mjnaderi** [comment]
That is not an error. It just says that when assignment finishes (after extra time), students can't change their _final_ submissions.

**Comment by linhtlthp** [comment]
![screenshot 10](https://cloud.githubusercontent.com/assets/11305086/6479761/1d16d7ec-c27d-11e4-9279-7034f30172e2.png)

why the system is always in condition pendding

**Comment by linhtlthp** [comment]
![screenshot 11](https://cloud.githubusercontent.com/assets/11305086/6479779/510393ba-c27d-11e4-9150-5cb50fd3a46b.png)

why the system is always in condition pendding

**Comment by linhtlthp** [comment]
please can you give me one of test samples!!

**Comment by linhtlthp** [comment]
I need your help to build the system !!
you can give yourself facebook!!

**Comment by linhtlthp** [comment]
Help me!! Compilation Error
https://github.com/mjnaderi/Sharif-Judge/issues/20

2015-03-04 13:44 GMT+07:00 Mohammad Javad Naderi notifications@github.com:

**Comment by mjnaderi** [comment]
You can find sample assignment in `assignments` folder.
I need to know what is the problem and what you have already done to find its source and solve it.
