### ISSUE TITLE
404 on the installation wizard

### ISSUE THREAD

**Issue by DanielYWoo** [mjnaderi/Sharif-Judge#2]
Open the browser and access http://localhost, you will be take to http://localhost/index.php/install, which is 404.

**Comment by MSDehghan** [comment]
but for me is not 404. do you set the database info in the database.php ???

**Comment by DanielYWoo** [comment]
Yes. If you leave database configuration empty, an SQL error shows. Once database is configured correctly, you will be redirected to index.php/install, then 404 shows up.  

## 

Daniel Wu
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by emacslisp** [comment]
It happens to me as well, No sure how to fix this one

at beginning it redirects to 
http://localhost/index.php/install and 404 shows up because this is not right URL

**Comment by mjnaderi** [comment]
That URL is OK, and it should not display 404. It should call `index()` function in `application/controllers/Install.php`.

Add this line to the beginning of `index()` function ([here](https://github.com/mjnaderi/Sharif-Judge/blob/Version-1/application/controllers/Install.php#L24)) and see what happens when you open `http://localhost/index.php/install`:

``` php
exit("This text should be displayed");
```

**Comment by emacslisp** [comment]
I add echo("some text!!!") to index() in install.php.

it displays correctly, 

and I also use command 'chmod 777 application/cache/Twig' to make Twig writable.

however, I still get an empty page with echo text

**Comment by mjnaderi** [comment]
Temporarily change environment to 'development' to see errors.

In `index.php`, change

``` php
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');
```

to

``` php
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
```
