### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#20]
![screenshot 12](https://cloud.githubusercontent.com/assets/11305086/6480274/b7147f6e-c284-11e4-9ca0-20e8eade8712.png)

**Comment by linhtlthp** [comment]
![screenshot 14](https://cloud.githubusercontent.com/assets/11305086/6484264/035547aa-c2ad-11e4-9664-dff7c61a5034.png)

**Comment by mjnaderi** [comment]
I cannot help. I need to know what is the problem and what you have already done to find its source and solve it.

**Comment by linhtlthp** [comment]
I have followed all instructions and use the correct form! why the error !!

**Comment by atiabjobayer** [comment]
I think you haven't installed the compilers on your server
