### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#21]
![screenshot 46](https://cloud.githubusercontent.com/assets/11305086/6540377/f731986c-c4cc-11e4-8124-973e847b89b8.png)

**Comment by mjnaderi** [comment]
More information is needed to investigate the problem. Check the log by clicking on Log button. And try running the command which is in the first line of log file, manually.

**Comment by linhtlthp** [comment]
![screenshot 72](https://cloud.githubusercontent.com/assets/11305086/6612519/7cbca85a-c8b0-11e4-88c2-ade0c1492b4c.png)

**Comment by linhtlthp** [comment]
i run 1th line on the file log. and result had no diffirent and still error

**Comment by linhtlthp** [comment]
Now I need to do to you can help me ??

**Comment by mjnaderi** [comment]
In this screenshot, the line `Output size limit: _size_limit bytes` is incorrect. Output size limit must be an integer. But it is `_size_limit`.
If your linux has SELinux enabled, disable it.
Also, try disabling EasySandbox and Shield in the settings page.

**Comment by linhtlthp** [comment]
![screenshot 86](https://cloud.githubusercontent.com/assets/11305086/6633249/5a5be7da-c978-11e4-8c08-e3c0c534137b.png)
I took off easysandbox and shield and the results remained 0 points

**Comment by linhtlthp** [comment]
![screenshot 87](https://cloud.githubusercontent.com/assets/11305086/6633283/c0ac1afa-c978-11e4-84af-eaed8c18e3b8.png)

**Comment by linhtlthp** [comment]
![screenshot 88](https://cloud.githubusercontent.com/assets/11305086/6633507/4391154e-c97c-11e4-9c9b-15dbdda196de.png)

**Comment by linhtlthp** [comment]
![screenshot 89](https://cloud.githubusercontent.com/assets/11305086/6633537/cc820c5a-c97c-11e4-9f52-3347ecbc7572.png)

**Comment by mjnaderi** [comment]
Thanks for the last screenshot, which describes the problem. I need things like this to know the problem.
You have followed instructions in wiki about security, but you have forgotten to create the user `another_user`. Read the [wiki page about security](http://docs.sharifjudge.ir/en:v1.4:security) once again.

**Comment by linhtlthp** [comment]
![screenshot 97](https://cloud.githubusercontent.com/assets/11305086/6650180/fc8df6c4-ca36-11e4-9b7f-7db07cabec0b.png)
![screenshot 98](https://cloud.githubusercontent.com/assets/11305086/6650179/fb1bbf7e-ca36-11e4-8161-ef1ffe115841.png)
I did as directed, but the runtime error

**Comment by mjnaderi** [comment]
The wiki says _Create a new user..._. Run `useradd another_user`.

**Comment by linhtlthp** [comment]
Thank you !! I'll try. Wish you always stay in touch

**Comment by linhtlthp** [comment]
![screenshot 101](https://cloud.githubusercontent.com/assets/11305086/6651291/ff83c646-ca6e-11e4-9507-cb2432c44bb4.png)
![screenshot 102](https://cloud.githubusercontent.com/assets/11305086/6651292/ffbca574-ca6e-11e4-8ad3-0c5af7c3b9bb.png)
I have created a user. and follow, but the result is still the same

**Comment by linhtlthp** [comment]
![screenshot 119](https://cloud.githubusercontent.com/assets/11305086/6654935/92b53118-cb17-11e4-9217-1d5c2ca92d60.png)

**Comment by linhtlthp** [comment]
![screenshot 120](https://cloud.githubusercontent.com/assets/11305086/6654948/354a7546-cb18-11e4-81ff-2672d45b7e4f.png)
10000 ??

**Comment by linhtlthp** [comment]
![screenshot 121](https://cloud.githubusercontent.com/assets/11305086/6654975/04c6627a-cb1a-11e4-848e-595e856a4e9c.png)

I have found a bug
That is because your code wrong!

**Comment by mjnaderi** [comment]
There is no problem with 10000. That's OK.
Seems the "Runtime Error" problem is solved. And you created #26 about the bug you found. So I close this issue.
