### ISSUE TITLE
Test bad 

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#22]
![image](https://cloud.githubusercontent.com/assets/11305086/6545148/3120d4d8-c5aa-11e4-983f-4fb55a2fde9e.png)

**Comment by mjnaderi** [comment]
More information is needed to investigate the problem.

**Comment by linhtlthp** [comment]
i used to your zip file item and upload it. then, i copy your answer to test. but result was 0 poin.. and notify runtime error

**Comment by mjnaderi** [comment]
Duplicate of #21. Closed.
