### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by linhtlthp** [mjnaderi/Sharif-Judge#25]
Can u help me . I'd like teamview with u or u can email for me.. I'm looking for u!

**Comment by mjnaderi** [comment]
_Issues_ page in Github is a better place to solve problems about Sharif Judge. Later, people with the same problem can find the solution here.

**Comment by linhtlthp** [comment]
But I find not such errors in it

**Comment by mjnaderi** [comment]
Yes, I know that. But I mean if we solve your problem in _Issues_ page instead of e-mail, later other people can find the solution.

**Comment by atiabjobayer** [comment]
Actually, I also need to contact you. It is better to give your email or other else
