### ISSUE TITLE
Can't upload the problems set from zip example

### ISSUE THREAD

**Issue by slakat** [mjnaderi/Sharif-Judge#3]
Hello, I downloaded the zip for the problems set example, but when I try the upload in SharifJudge it says that isn't supported the format.

**Error: Error uploading tests zip file: The filetype you are attempting to upload is not allowed.**

I downloaded it from here http://sharifjudge.ir/docs/sample/sample_assignment_v1.4.zip

greetings.

**Comment by mjnaderi** [comment]
Hi,
In `application/controllers/Assignments.php`, change

``` php
$config = array(
    'upload_path' => $assignments_root,
    'allowed_types' => 'zip',
);
```

to

``` php
$config = array(
    'upload_path' => $assignments_root,
    'allowed_types' => '*',
);
```

https://github.com/mjnaderi/Sharif-Judge/blob/v1.4/application/controllers/Assignments.php#L428

**Comment by mjnaderi** [comment]
You can also put tests manually in `assignments` directory: `assignments/assignment_1/[p1, p2, ...]`, `assignments/assignment_2/[p1, p2, ...]`, ...

**Comment by slakat** [comment]
It worked. Thank you, This judge  is amazing, we're using it to teach students how to program through challenges.

**Comment by linhtlthp** [comment]
You cannot change your final submissions after assignment finishes
