### ISSUE TITLE
Installation blank screen

### ISSUE THREAD

**Issue by alexbagirov** [mjnaderi/Sharif-Judge#30]
Hello!

I am trying to install the script but see the blank screen (not installation page). What should I do?

**Comment by mjnaderi** [comment]
Temporarily change environment to 'development' to see errors.

In `index.php`, change

``` php
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');
```

to

``` php
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
```

**Comment by alexbagirov** [comment]
You can see it here: http://judge-alexbagirov.c9.io
The page loads but nothing happens.

**Comment by truongan** [comment]
Check you database connection. If the errors is database related it won't show, even if you switched to development environment

**Comment by aidarbek** [comment]
I had the same issue. Making "application/cache/Twig" directory writable by everyone helped me.

**Comment by mjnaderi** [comment]
Thanks @aidarbek.
You need to make `application/cache/Twig` writable by the user running php.
Allowing all users to write to this directory is not secure. Find the user running php, and allow writing for that user. If you are using Apache web server on Ubuntu, the user is `www-data`.

**Comment by mjnaderi** [comment]
@alexbagirov  I tried to install a fresh copy of Sharif Judge, and there was blank screen. The problem was that I forgot to enable `mysqli` extension for php in `php.ini`. After enabling `mysqli` extension for php and restarting the web server, problem solved.

**Comment by parthg** [comment]
Hi, I am trying to install Sharif judge on Fedora. Initially I was getting the blank screen, then I changed to the development mode. Also I changed the permission to 755 with "apache" user for the webserver. I get following error:

```
Warning: require_once(/var/www/html/judge/system/core/CodeIgniter.php): failed to open stream: Permission denied in /var/www/html/judge/index.php on line 285

Fatal error: require_once(): Failed opening required '/var/www/html/judge/system/core/CodeIgniter.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/judge/index.php on line 285
```

Currently system and application are in the same root directory of index.php

Any help would be highly appreciated. Thanks!

**Comment by tawanchaiii** [comment]
I have Installation blank screen issue too. I want to watch how to install in video .

**Comment by enkerewpo** [comment]
Actually I changed the permission to 777 and owner to apache:apache for all files in the website folder but still got this:
```
A PHP Error was encountered
Severity: Error
Message: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/html/application/cache/Twig/d2/87).' in /var/www/html/application/third_party/Twig/lib/Twig/Environment.php:1236 Stack trace: #0 /var/www/html/application/third_party/Twig/lib/Twig/Environment.php(334): Twig_Environment->writeCacheFile('/var/www/html/a...', 'loadTemplate('pages/admin/ins...') #2 /var/www/html/application/controllers/Install.php(276): Twig->display('pages/admin/ins...', Array) #3 [internal function]: Install->index() #4 /var/www/html/system/core/CodeIgniter.php(356): call_user_func_array(Array, Array) #5 /var/www/html/index.php(285): require_once('/var/www/html/s...') #6 {main} thrown
Filename: Twig/Environment.php
Line Number: 1236
```

And linux is `CentOS 7.3` with version `3.10.0-514.26.2.el7.x86_64`.....

**Comment by enkerewpo** [comment]
I got the answer to my problem.
It's because __SElinux__ on `CentOs`  that banned apache from creating files....
If you are just testing your website now. You can try log into `root` and type `$ setenforce 0` to disable it temporarily.

**Comment by DiegoQueiroz** [comment]
Disabling SELinux is always the lazy solution.

Before choosing a distro, you should learn how to use it. SELinux is enabled by default for a reason.

**Comment by enkerewpo** [comment]
@DiegoQueiroz Thanks for the reply. 
That's right, and I just found something that `SElinux` could just customize the settings to make the website safe and available.
Actually this is my first time using `CentOS` which is very different from `Debian`, and I just made a progress to get to know my new system...You know it's exciting to fix the problem after trying for hours.
