### ISSUE TITLE
add code editor in the problem description page

### ISSUE THREAD

**Issue by mars00772** [mjnaderi/Sharif-Judge#31]
sharif-judge is nice ,I like it's ui style indeed.if we can edit and submit code in the problem description page would be nice.

**Comment by mjnaderi** [comment]
Thanks for your suggestion. This is easy to implement. But I'm not going to implement it.
You can use Ace Editor to achieve this.

**Comment by BakhodirIsmatov** [comment]
Hello, I want to add textarea in problem page for submition. please help me! ho I do it?
