### ISSUE TITLE
Database details 

### ISSUE THREAD

**Issue by ghost** [mjnaderi/Sharif-Judge#33]
I have read the instructions of installation, when hit this : "**Create a MySql or PostgreSql database for Sharif Judge. Do not install any database connection package for C/C++, Java or Python.**"
I did not know what the database should I create ? 
I created an empty database and I set the settings as it was mentioned in the 4th instruction, but still show a blank page when I try to open the main page .
what are the tables and the fields I should create in order to run the judge ?
Thank you for taking time to read my issue .
Hope you help me .

**Comment by truongan** [comment]
You should create an empty database. And double check, triple check your database settings.

**Comment by atiabjobayer** [comment]
Have you edited the index.php file as application and system folder path?
