### ISSUE TITLE
Java Exceptions Security Risk

### ISSUE THREAD

**Issue by MJafarMashhadi** [mjnaderi/Sharif-Judge#4]
I understand you have restricted stderr to only show valid java exceptions and preventing user to display information by printing them into error stream, but i guess ShJ is still vulnerable to this code:

public static void main(String[] args) {
   throw new java.lang.Exception("Important stuff like test case inputs or result of executing shell commands");
}

**Comment by mjnaderi** [comment]
It just prints

```
Test 1
Runtime Error (java.lang.Exception)
Test 2
Runtime Error (java.lang.Exception)
...
```

And exception message is not printed.
Have you tested it?

**Comment by MJafarMashhadi** [comment]
No, it just came to my mind.

**Comment by mjnaderi** [comment]
Sharif Judge does not print anything that does not exist in this file: https://github.com/mjnaderi/Sharif-Judge/blob/Version-1/tester/java_exceptions_list
I'm not a Java expert. So, If you think a useful java exception is missing in this file, or one of this file's exceptions is useless or introduces vulnerability, please send a Pull Request for that.
If you found any other vulnerability about Java Exceptions, feel free to report it.
