### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by TheHolyLoli** [mjnaderi/Sharif-Judge#47]
Hello,I tried installing Sharif judge on my Ubuntu 16.04 (Desktop).
I configured required files like `database.php` and `index.php`
I made `application/cache/twig` writable by `www-data`
I opened the installation page,and i entered admin username-email and password.but when Sharif-judge is trying to make database ready,it gets an error:
1. Sharif judge connects to the MySQL database successfully(with username: `root`,as i don't mind about the security)
2. Sharif judge makes table : `shj_sessions`
3. Sharif judge makes table : `shj_submissions`
4. It gives error while making table: `shj_assignments`

Here are the screenshots:
![screenshot](https://i.imgsafe.org/f79f090197.png)
### Edit(Added screenshot of tables):

![screenshot](https://i.imgsafe.org/f7c27ccdce.png)
### My system information:

OS : Ubuntu16.04
PHP Version : 7.0.4-7ubuntu2.1
MySQL Version : 5.7.12-0ubuntu1
### what i have already tried:
- [x] re-installing sharif-judge
- [x] reinstalling apache2 and mysql and php,replacing php7.0 with php5.6

**Comment by ghost** [comment]
Blob/text columns can't have a default value, not even the empty string in MySQL.

You should remove all default value of text columns in `install.php`

**Comment by tahmidrafi** [comment]
To make it work I had to remove all the default values for TEXT type columns from the installation script. MySQL doesn't support default values for TEXT type data.

**Comment by chez14** [comment]
This should not be closed as nobody updates the code.

**Comment by chez14** [comment]
@madl-ash can you reopen this? Other people may struggle finding out the root of problem.
