### ISSUE TITLE
Java network security risk

### ISSUE THREAD

**Issue by MJafarMashhadi** [mjnaderi/Sharif-Judge#5]
I don't know if used sandboxes used in ShJ do block network connections or not.
I, myself during the usinversity semester that i took AP in Java course, did steal test cases from judge using a simple network connection. Also i granted shell access to server which JAJ(Java Assignments Judge) was running on.

**Comment by mjnaderi** [comment]
Sharif Judge is using Java Security Manager when running java codes. As I tested, it blocks network access. Actually, I don't know how much I can rely on it :)
So, for more restriction, (and also for C/C++ and Python), in step 3 of [this page](http://docs.sharifjudge.ir/en:v1.4:security), I have explained how to run submitted codes as an unprivileged linux user which does not have network access (using iptables), and has more restrictions.

**Comment by mjnaderi** [comment]
If you want to test security issues of Sharif Judge, I suggest that you install Sharif Judge on your local computer (with all these security mechanisms: http://docs.sharifjudge.ir/en:v1.4:security) and If you found a vulnerability, please send me an email or report it on Github :)
