### ISSUE TITLE
Testcases

### ISSUE THREAD

**Issue by wojcik13** [mjnaderi/Sharif-Judge#50]
Hello,
I think, that there is need to make a function to add testcases directly from web gui, because I can't give to some head instructors access to my VPS.
Kindly regards c:

**Comment by mjnaderi** [comment]
Hi,
This is possible. You can upload test cases as a zip file from web interface.
https://github.com/mjnaderi/Sharif-Judge/blob/docs/v1.4/add_assignment.md#tests
