### ISSUE TITLE
Folder writable problem

### ISSUE THREAD

**Issue by satyapendem** [mjnaderi/Sharif-Judge#57]
The folder "/home/satyapendem/assignments" is not writable by PHP. Make it writable. But make sure that this folder is only accessible by you. Codes will be saved in this folder!

The folder "/home/satyapendem/tester" is not writable by PHP. Make it writable. But make sure that this folder is only accessible by you.

![error](https://cloud.githubusercontent.com/assets/14092224/20673213/41cfa358-b5aa-11e6-9806-d3fb3b259f39.png)

**Comment by truongan** [comment]
Go to Settings and change assignment and testing folder to some where PHP can write (where you did install sharif judge).

and btw, how did you get that look, my installation look much different.
