### ISSUE TITLE
Blank screen.

### ISSUE THREAD

**Issue by hazimfrodo** [mjnaderi/Sharif-Judge#6]
I am not really good in setting up sharif-judge , but when i tried to load the index.php..
i got blank white page..how to solve this problem ?

**Comment by hazimfrodo** [comment]
nvm..got it solved..i removed postgresql..n install mysql..
seems like mysql is easier to operate rather than postgresql..
anyway..thanks

**Comment by mjnaderi** [comment]
You're welcome (:
